
BEGIN TRANSACTION;

CREATE table codejudge.USERS
(
    ID          SERIAL,
    USERNAME    VARCHAR NOT NULL,
    PASSWORD    VARCHAR NOT NULL,
    FIRSTNAME   VARCHAR NOT NULL,
    LASTNAME    VARCHAR NOT NULL,
    EMAIL       VARCHAR NOT NULL,
    REGISTRATION_TIME TIMESTAMP NOT NULL,
    USER_ROLE   INT NOT NULL,
    PRIMARY KEY(ID)
);

CREATE table codejudge.PROBLEMS
(
    ID                   SERIAL, 
    PROBLEM_TEXT         VARCHAR(255) NOT NULL,
    NUMBER_TEST_CASES    VARCHAR(255) NOT NULL,
    PRIMARY KEY(ID)
);

CREATE table codejudge.GROUPS
(
    ID SERIAL,
    INSTRUCTOR_ID   INT NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(INSTRUCTOR_ID) 
    REFERENCES codejudge.USERS(ID)
    ON DELETE SET NULL    
);

CREATE table codejudge.USER_PROBLEM
(
    ID          SERIAL,
    USER_ID     INT,
    PROBLEM_ID  INT,
    PRIMARY KEY(ID),
    FOREIGN KEY (USER_ID) REFERENCES codejudge.USERS(ID)
    ON DELETE SET NULL,
    FOREIGN KEY (PROBLEM_ID) REFERENCES codejudge.PROBLEMS(ID)
    ON DELETE SET NULL
);

CREATE table codejudge.GROUP_PROBLEM
(
    ID          SERIAL,
    GROUP_ID     INT,
    PROBLEM_ID  INT,
    PRIMARY KEY(ID),
    FOREIGN KEY (GROUP_ID) REFERENCES codejudge.GROUPS(ID)
    ON DELETE SET NULL,
    FOREIGN KEY (PROBLEM_ID) REFERENCES codejudge.PROBLEMS(ID)
    ON DELETE SET NULL
);

CREATE table codejudge.TEST_CASES
(
    ID          SERIAL,
    TESTCASE_USER_ID    INT NOT NULL,
    TESTCASE_PROBLEM_ID INT NOT NULL,
    EXAMPLE_TEST_CASE   INT NOT NULL,
    VISIBLE             INT,
    PRIMARY KEY(ID),
    FOREIGN KEY (TESTCASE_USER_ID) REFERENCES codejudge.USERS(ID)
    ON DELETE SET NULL,
    FOREIGN KEY (TESTCASE_PROBLEM_ID) REFERENCES codejudge.PROBLEMS(ID) 
    ON DELETE SET NULL
);

CREATE table codejudge.ATTEMPTS
(
    ID SERIAL,
    ATTEMPT_USER_ID      INT NOT NULL,
    ATTEMPT_PROBLEM_ID   INT NOT NULL,
    ATTEMPT_TESTCASE_ID  INT NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY (ATTEMPT_USER_ID) REFERENCES codejudge.USERS(ID) ON DELETE SET NULL,
    FOREIGN KEY (ATTEMPT_PROBLEM_ID) REFERENCES codejudge.PROBLEMS(ID) ON DELETE SET NULL,
    FOREIGN KEY (ATTEMPT_TESTCASE_ID) REFERENCES codejudge.TEST_CASES(ID) ON DELETE SET NULL
);
COMMIT;
